platform :ios, "8.0"
target "HealthMonitoringSystem" do
pod "AFNetworking", "~> 3.1.0"
pod "SDWebImage", "~> 4.0"
pod "SVProgressHUD", "~> 2.0.3"
pod "MJExtension", "~> 3.0.10"
pod "MJRefresh", "~> 3.1.0"
pod "Masonry", "~> 1.0.0"
pod 'YYCache'
pod "IQKeyboardManager", "~> 4.0.8"
pod "Qiniu", "~> 7.0"
# 富文本
pod "YYText", "~> 1.0.5"
end
